language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

# ===== operating systems =====
os:
    - linux
    - osx

#compiler:
#   - g++
#   - clang


# ===== install dependencies =====

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:cython-dev/master-ppa   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update                                         ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=~/usr/bin:$PATH                            ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_ttf   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glm        ; fi
#     TODO: install SOIL from source for osx

# all
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libsdl2-dev        ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libsdl2-ttf-dev    ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install cython3            ; fi
#    - pip3 install -r requirements.txt

# ubuntu
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libglew-dev
        - libsoil-dev
        - libglm-dev
#        - python3-pip

# ===== run tests =====
env:
    - TEST_SUITE=core
    - TEST_SUITE=graphics
    - TEST_SUITE=gui
    - TEST_SUITE=input
    - TEST_SUITE=physics
    - TEST_SUITE=prototypes
    - TEST_SUITE=sound
script: "make test-$TEST_SUITE"

