language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

# ===== operating systems =====
os:
    - linux
    - osx

#compiler:
#   - g++
#   - clang


# ===== install dependencies =====

# ubuntu
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libsdl2-dev
        - libsdl2-ttf-dev
        - libglew-dev
        - libsoil-dev
        - libglm-dev
        - cython3
#        - python3-pip

# OSX
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo add-apt-repository ppa:zoogie/sdl2-snapshots; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo add-apt-repository ppa:cython-dev/master-ppa; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_ttf   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glm        ; fi
#     TODO: install SOIL from source

# all
install:
#    - pip3 install -r requirements.txt

# ===== run tests =====
env:
    - TEST_SUITE=core
    - TEST_SUITE=graphics
    - TEST_SUITE=gui
    - TEST_SUITE=input
    - TEST_SUITE=physics
    - TEST_SUITE=prototypes
    - TEST_SUITE=sound
script: "make test-$TEST_SUITE"

