language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6-dev"
    - pypy
    - pypy3

# ===== general settings =====

notifications:
    email: false

# ===== testing systems =====

os:
    - linux

#compiler:
#   - g++
#   - clang

matrix:
    allow_failures:
        - python: pypy
        - python: pypy3
        - python: 3.5-dev
        - python: 3.6-dev
        - os: osx
    include:
        - os: osx
          language: generic
          python: 2.7
        - os: osx
          language: generic
          python: 3.5

# ===== install dependencies =====

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh .before_install_linux.sh      ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo sh .before_install_osx.sh          ; fi

# all
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh .install_linux.sh             ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo sh .install_osx.sh                 ; fi
    - sudo sh .install_python.sh
#    - if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]]; then sudo sh .install_python2.sh        ; fi
#    - if [[ "$TRAVIS_PYTHON_VERSION" == pypy ]]; then sudo sh .install_python2.sh       ; fi
#    - if [[ "$TRAVIS_PYTHON_VERSION" == 3.* ]]; then sudo sh .install_python3.sh        ; fi
#    - if [[ "$TRAVIS_PYTHON_VERSION" == pypy3 ]]; then sudo sh .install_python3.sh      ; fi

# ubuntu
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libglew-dev
        - libsoil-dev
        - libglm-dev
        - python3-venv

# ===== run tests =====

# Run all tests at once
script:
    - make
    - coverage run --source=core,graphics,gui,input,physics,prototypes,sound tests/allTests.py

# ===== post-testing =====
after_success:
    coveralls

