language: python
python:
	- "3.2"
	- "3.3"
	- "3.4"
	- "3.5"

# ===== operating systems =====
os:
	- linux
	- osx

#compiler:
#	- g++
#	- clang

sudo: required

matrix:
	include:
		- os: linux
		  sudo: required
		  python: 3.2
		  env: TOXENV=py32
		- os: linux
		  sudo: required
		  python: 3.3
		  env: TOXENV=py33
		- os: linux
		  sudo: required
		  python: 3.4
		  env: TOXENV=py34
		- os: linux
		  sudo: required
		  python: 3.5
		  env: TOXENV=py35
		- os: osx
		  language: generic
		  env: TOXENV=py32
		- os: osx
		  language: generic
		  env: TOXENV=py33
		- os: osx
		  language: generic
		  env: TOXENV=py34
		- os: osx
		  language: generic
		  env: TOXENV=py35

# ===== install dependencies =====

# ubuntu
addons:
	apt:
		packages:
		- libsdl2-dev
		- libsdl2-ttf-dev
		- libglew-dev
		- libsoil-dev
		- libglm-dev
		- python3-pip
		- cython3

# OSX
before_install:
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update				; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2		; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_ttf	; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew		; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glm		; fi
#	TODO: install SOIL from source

# all
install: 
	- pip3 install -r requirements.txt

# ===== run tests =====
env:
	- TEST_SUITE=core
	- TEST_SUITE=graphics
	- TEST_SUITE=gui
	- TEST_SUITE=input
	- TEST_SUITE=physics
	- TEST_SUITE=prototypes
	- TEST_SUITE=sound
script: "make test-$TEST_SUITE"

